import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";

import Navbar from "../src/components/Navbar";
import MintNow from "../src/components/MintNow";
import AutoCarousel from "../src/components/AutoCarousel";
import Footer from "../src/components/Footer";
import FeaturedIn from "../src/components/FeaturedIn";
import MeetThePunks from "../src/components/MeetThePunks";
import PunkDetails from "../src/components/PunkDetails";
import DetailsAndFaq from "../src/components/DetailsAndFaq";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <MintNow/>
      <AutoCarousel/>

      <FeaturedIn/>
      <MeetThePunks/>
      <PunkDetails/>

      <DetailsAndFaq/>
      <Footer/>

    </div>
  );
};

export default Home;
